### ISSUE TITLE
Limit the upvote amount for a period of time

### ISSUE THREAD

**Issue by thibautsailly** [AvdLee/Roadmap#15]
If a roadmap contains 10 items, and the user can vote once for each of them, the votes will bring no insight to the app's developper.
If the user knows 2 or 3 items only can be upvoted, her contribution will be more meaningful.
Reseting the limit periodically would maintain the usefulness of Roadmap in an app overtime, and allow the user to participate to items updates.

The dev would set: each user can upvote [x] item(s) every [y] months.
The user would see: "You have x items left to vote for", and when none are left "you can vote again in y-z months", z being the number of months elapsed since the most past vote was cast.

**Comment by jordibruin** [comment]
But what if the person really wants all 10 features? Limiting what people can vote on would just de-incentivise people to vote on features they like. For every person that votes for all features, there will be people that vote on just their favourites, so in the long term I don't think it has an impact.

That being said, feel free to make a PR with an optional vote limit feature. Resetting this vote limit after a certain time would be wise, but how would we make people aware of it? I think it comes with a bunch of UX challenges to solve.

**Comment by thibautsailly** [comment]
Think of it as a way of letting the developper increase contrast on the picture taken from this user feedback.

> But what if the person really wants all 10 features?

The proposed solution could allow users to vote for all items, if the developper wanted them to. With 10 features to vote for, a dev who would like the maximum number of users to be able to vote for any of them can set x to 10.

> Limiting what people can vote on would just de-incentivise people to vote on features they like.

Possibly, but you get feedback from really motivated users who made a choice, which is valuable. But again, the solution doesn't force the dev to make it work this way.

> For every person that votes for all features, there will be people that vote on just their favourites, so in the long term I don't think it has an impact.
This is true when the user sample is large, not so if you only have a couple hundreds. A situation worth considering for this tool helping you prioritise work at early stage of development.

> how would we make people aware of it?

On top of the items list, there could be a "5 votes remaining until 1st of July" label. Every January 1st and July 1st the limit could be reset.

Thank you for the invitation do make a PR, but I don't code :-/.

**Comment by jordibruin** [comment]
Thanks for the extra insights. I think it would be nice to add this as an option. We'll have to figure out the best way to approach this.

**Comment by jordibruin** [comment]
https://github.com/AvdLee/Roadmap/pull/45

With this or you can disallow people from voting after x amount of votes for example!
