### ISSUE TITLE
Support for localization 

### ISSUE THREAD

**Issue by cs4alhaider** [AvdLee/Roadmap#17]
It would be nice to support for multiple languages, we need to think on how we can implement this either to have different APIs or to have extra JSON keys for for `title` 

For example, I think this will be a good approach:
```
[
  {
    "id": "1",
    "title": "Adding a map",
    "localized_title": [
      {
        "language": "ar",
        "value": "اضافة خارطة"
      },
      {
        "language": "en",
        "value": "Adding a map"
      }
    ],
    "status": "planned", // This also can be the same as title
    "description": "some description" // This also can be the same as title
  }
]
```

**Comment by cs4alhaider** [comment]
I have opened a [PR](https://github.com/AvdLee/Roadmap/pull/19) for this.

**Comment by jordibruin** [comment]
Thanks a lot for your work on this!

**Comment by cs4alhaider** [comment]
Thanks to u guys for such idea! 
@jordibruin @hiddevdploeg @AvdLee

**Comment by dickieee** [comment]
I am noticing localisation for Chinese simplified and traditional are not working. Other languages work correctly.

**Comment by cs4alhaider** [comment]
@dickieee feel free to fork the repo and make the adjustments and file a PR
