### ISSUE TITLE
Background Color of List

### ISSUE THREAD

**Issue by JamesSedlacek** [AvdLee/Roadmap#23]
I need the ability to change the background color of the list to match the rest of my app

**Comment by JamesSedlacek** [comment]
Another option would be the ability to change the color of the background & cells

**Comment by JamesSedlacek** [comment]
<img width="416" alt="Screenshot 2023-02-21 at 2 33 45 PM" src="https://user-images.githubusercontent.com/54433817/220441231-eb466db6-4da5-415a-b375-c47c47928a2d.png">
<img width="424" alt="Screenshot 2023-02-21 at 2 33 37 PM" src="https://user-images.githubusercontent.com/54433817/220441238-ed0a91e4-a8d2-4635-90ad-5da98425d46d.png">

**Comment by AvdLee** [comment]
You can do that as follows:

```swift
RoadmapView(configuration: configuration)
    .scrollContentBackground(.hidden)
    .background(Color.red)
```

Let me know if that didn't work out and I'm happy to reopen.

**Comment by JamesSedlacek** [comment]
<img width="1378" alt="Screenshot 2023-02-22 at 10 12 45 AM" src="https://user-images.githubusercontent.com/54433817/220665332-90b10693-f712-47e2-aea1-2f477b138125.png">

Unfortunately that isn't working

**Comment by jordibruin** [comment]
@AvdLee that didn't seem to do the trick

**Comment by hiddevdploeg** [comment]
I fixed this in the latest PR that just got merged :D

**Comment by JamesSedlacek** [comment]
@hiddevdploeg you're killing it! Thanks!
