### ISSUE TITLE
Sync with GitHub issues with `roadmap` label, upvotes are 👍

### ISSUE THREAD

**Issue by austincondiff** [AvdLee/Roadmap#27]
It would be great if this could instead pull from GitHub issues that had a `roadmap` label, or any user-specified label.

Upvotes would translate into 👍 on GitHub. The user would need to authenticate with GitHub when attempting to interact. We may provide a link to the issue on GitHub as well.

**Comment by hiddevdploeg** [comment]
Although I’m all for having integrations setup for this, I think the critical aspect here is “**the user would need to authenticate with Github**” 

_If you’re referring to the developer implementing this_
This could be an optional addition in the future, for now we want to keep things as simple as possible 

_If you’re referring to the user of the roadmap_
This would increase the bar to actually vote on items by a lot and this bar needs to be as low as possible for this feature to work
