### ISSUE TITLE
Set requirements for users to vote

### ISSUE THREAD

**Issue by JamesSedlacek** [AvdLee/Roadmap#34]
I'd like the ability to set requirements in order for users to vote.
This would prevent competitors or random new users from voting.

**Comment by jordibruin** [comment]
How would you see this working with our current api approach?

**Comment by JamesSedlacek** [comment]
Would just need to pass in a Boolean for if the user is eligible for voting & pass in a closure (ineligibleHandler?) for if they try to vote & aren't allowed to. 

I have the RoadmapView inside of a RoadmapContainerView that I created & I'd create a viewModel for that which would have a method that calculates if the user is eligible for voting & it'd also handle presenting a toast message if they try to vote & haven't met the requirements yet.

This does add complexity to the Roadmap library, but I feel like a lot of devs would like this functionality.

**Comment by jordibruin** [comment]
Hm, wouldn’t the more simple approach be to not show the roadmap to people who are not allowed to vote? Or would you want to show it to them in read only mode?

**Comment by JamesSedlacek** [comment]
Read-only mode could work

**Comment by AvdLee** [comment]
Maybe we should leverage SwiftUI for this with the `disabled(true)` modifier and respect that? 
Or maybe: @JamesSedlacek can you try to set `RoadmapView(configuration ...).allowsHitTesting(false)` and see if that works for you?

**Comment by JamesSedlacek** [comment]
@AvdLee neither of these solve the problem. 
Both completed remove the ability to scroll & disabled makes the vote button greyed-out. 
I think applying allowsHitTesting to the vote button could work?
& pass into the configuration a Boolean property for if read-only mode is enabled?
With a default value of false, of course
`isReadOnlyModeEnabled: Bool = false`

**Comment by AvdLee** [comment]
@JamesSedlacek too bad! In that case, I think we could add a `isVotingEnabled` property to the configuration object. Would that work?

**Comment by JamesSedlacek** [comment]
Yeah that would work!

**Comment by jordibruin** [comment]
https://github.com/AvdLee/Roadmap/pull/45

Made a first pass at it

**Comment by AvdLee** [comment]
Fixed with https://github.com/AvdLee/Roadmap/pull/45
