### ISSUE TITLE
Don't do api call for features that are finished

### ISSUE THREAD

**Issue by jordibruin** [AvdLee/Roadmap#36]
I would want to keep a list of all "finished" features as well, but I don't want to show the votes for these features anymore.

Since the status can be anything, I'm not sure if there's a way to link it to that, but maybe we can think of a way to hide the votes for particular situations.

**Comment by anmolmalhotra** [comment]
We can add a isFinished key in the JSON. If it is true, app will hide the votes view.

```json
[
    {
        "id": "1",
        "title": "Combine sentences",
        "status": "finished",
        "description" : "You can add a little bit of extra context here.",
        "isFinished": true
    },
    {
        "id": "2",
        "title": "Open with Finder support",
        "status": "planned"
    }
]
```
