### ISSUE TITLE
Add support for iOS 15

### ISSUE THREAD

**Issue by rafaelclaycon** [AvdLee/Roadmap#48]
My project has a minimum deployment target of iOS 15.0. I understand that this was a choice made to make Roadmap's development easier and more fun and it's ok. I'm planning on showing the feature only to iOS 16 users, but when I try to import it on my SwiftUI view, Xcode complains the framework is iOS 16 only.

![Screenshot 2023-02-27 at 13 25 45](https://user-images.githubusercontent.com/5100081/221622350-53305071-cd02-4629-84eb-825836bfe98c.png)

As you can see, I tried `@available` and `canImport`, but the first does not work for imports and the latter is only good for checking platform (i.e. Mac, iOS, watchOS, etc).

Any tips?

**Comment by jordibruin** [comment]
Roadmap only supports iOS 16. If you want to add support for older versions you can make a PR with the required changes but for now we wanted to keep it simple to start.

**Comment by jordibruin** [comment]
Oh sorry I misread your question @rafaelclaycon !

@AvdLee any idea why this is happening?

**Comment by rafaelclaycon** [comment]
Thank you.

**Comment by anmolmalhotra** [comment]
@rafaelclaycon @jordibruin this is not possible as far as I know unless we add support for iOS 15.

**Comment by jordibruin** [comment]
We support iOS 15 now (not properly tested in all scenarios).
