### ISSUE TITLE
App icon too small

### ISSUE THREAD

**Issue by raffeyang** [AvdLee/Roadmap#52]
PlPlease update the app icon to conform to the macos specification. The app icon looks smaller than the mac standard

**Comment by jordibruin** [comment]
Do you mean for the example app? @hiddevdploeg

**Comment by raffeyang** [comment]
> Do you mean for the example app? @hiddevdploeg

Open Launchpad compare apple default app icon or other app icon, whisper transcription's icon sizz look smaller.
![CleanShot 2023-03-05 at 21 42 08@2x](https://user-images.githubusercontent.com/7557357/222964058-87fee9bf-0b80-4e37-919b-8c4a902b2d40.png)
<img width="429" alt="CleanShot 2023-03-05 at 21 43 24@2x" src="https://user-images.githubusercontent.com/7557357/222964125-94d62e57-04d1-4883-a32c-545dc65b0d78.png">

**Comment by jordibruin** [comment]
Ah, this is the repo for Roadmap, but I'll fix it, thanks for letting me know!

**Comment by raffeyang** [comment]
I've create one for you
![CleanShot 2023-03-08 at 18 30 46@2x](https://user-images.githubusercontent.com/7557357/223689480-6562f195-52c2-4c47-92fa-a177df38e93f.png)
[](url)
download here:
[AppIcon.icns.zip](https://github.com/AvdLee/Roadmap/files/10919630/AppIcon.icns.zip)
