### ISSUE TITLE
Failing to Compile

### ISSUE THREAD

**Issue by Sherlouk** [AvdLee/Roadmap#53]
@AvdLee - looks like recent changes were merged which caused the app to fail to compile. This means v1 is not currently working.

One example is the change to configuration initialisers.

https://github.com/AvdLee/Roadmap/blob/main/Sources/Roadmap/RoadmapConfiguration.swift#L37-L61

Notice how only one defines `allowSearching`.

**Comment by jordibruin** [comment]
Thanks, fixed it 👍
