### ISSUE TITLE
Searchable on Feature.description

### ISSUE THREAD

**Issue by vdhamer** [AvdLee/Roadmap#65]
The `Search` bar currently only searches the title of each Feature. It ignores the descriptions.

On the one hand, the number of roadmap items to vote on shouldn’t be too long. So `Search` is not too important.

On the other hand, because you _do_ support an optional `Search` bar, why not have it search the descriptions and titles simultaneously? After all, the user can’t predict exactly how `Search`works. And the user may not know if the search text is part of the title.

Q: should the Title <> Title+Description need to be configurable for developers?
A: it can obviously be done (Bool > enum?), but probably ok to just switch from Title only to Title+Description. It won’t really break anything, and users will see it as a bug fix. If they notice at all 🤔

If you want me to implement it, let me know preference w.r.t. configurability question.

**Comment by AvdLee** [comment]
Makes total sense for me to implement this!

**Comment by vdhamer** [comment]
There is already a (pretty simple) pull request for this.
