### ISSUE TITLE
Virtual Camera?

### ISSUE THREAD

**Issue by Jonatthu** [AvdLee/Roadmap#75]
Android emulator somehow did, iOS simulator for too long have not supported a virtual camera or using the hardware camera from the host. Any way to implement this?

**Comment by AvdLee** [comment]
If I'm not mistaken, this is a request for RocketSim. See the repo [here](https://github.com/AvdLee/RocketSimApp/issues).
Nevertheless: unfortunately, this is not possible for me to do. Would've been great though!
