### ISSUE TITLE
Link for simplejsoncms.com in ReadMe is pointing to a version that doesn't work

### ISSUE THREAD

**Issue by MaartenBorsje** [AvdLee/Roadmap#77]
In the read me file is a link to https://simplejsoncms.com but this doesn't work anymore. See https://medium.com/@jenshandersson/a-super-simple-json-cms-921e17cb25d9.

**Comment by AvdLee** [comment]
Thanks for reporting in! Feel free to open a PR with a fix accordingly 🙏

**Comment by MaartenBorsje** [comment]
Here is the pr #82
